name: foodly
description: "A pantry manager with recipe suggestions."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^4.0.1
  provider: ^6.0.0
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

flutter_native_splash:
  android: true
  color: "#121212"
  color_dark: "#121212"
  image: assets/icon.png
  android_12:
    color: "#121212"
